### ISSUE TITLE
Autogenerate additional merged records with documentation via `local-setup`

### ISSUE THREAD

**Issue by JordanMartinez** [justinwoo/spacchetti#32]
IMO, it would be nice if `local-setup` automatically generated two things in addition to what it already does:
1. additional records that it automatically merges, making it easy to add new packages or override upstream packages
2. instructions for how to add/override packages via comments. 

In other words, something like this:
```haskell
   let mkPackage = -- normal stuff
in let upstream  = -- upstream dhall stuff
in let overrides = {- 
    To override packages defined in the upstream packages
    with new values (e.g. update a tag, use a different git repo, etc.),
    replace the below '{=}' with something like the following
    for each package you need to update
-------------------------------
    { packageName =
        upstream.packageName ⫽ { updateEntity1 = "new value", updateEntity2 = "new value" }
    , packageName =
        upstream.packageName ⫽ { version = "v4.0.0" }
    , packageName =
        upstream.packageName // { repo = "https://www.example.com/path/to/new/repo.git" }
    }
------------------------------- -}
    {=}
in let additions = {- 
    To add packages not defined in the upstream packages,
    replace the below '{=}' with something like the following
    for each package
-------------------------------
    { "package-name" = 
          mkPackage
              [ "dependency1"
              , "dependency2"
              ]
              "https://example.com/path/to/git/repo.git"
              "tag ('v4.0.0') or branch ('master')"
    , etc...
    }
------------------------------- -}
    {=}
in upstream // overrides // additions
```
Then, a newcomer can follow the instructions in the generated file without needing to understand Dhall.

**Comment by justinwoo** [comment]
Unfortunately, I think all of those comments would get wiped out by Dhall-format, so they'd all have to go to the top level, but this sounds good. Don't know what the best way of getting template files would be though.

**Comment by f-f** [comment]
@justinwoo I usually use [dhall-to-text](https://github.com/dhall-lang/dhall-text)

**Comment by JordanMartinez** [comment]
@f-f I'm not familiar with Dhall, nor dhall-to-text. How could we use dhall-to-text to add in those comments?

**Comment by f-f** [comment]
`dhall-to-text` is a general templating solution, but since in this case we have a Haskell application, we can just depend on `dhall` and use it straight. Basically it would look something like that:
- we have a `template.dhall` file, that is a function that takes a record of `Text`s and returns a string interpolating the values in the right places
- from `spacchetti-cli` we read this file and call the function with the right params

I don't know if there's actually anything to "template" here though, so I'm not sure what @justinwoo meant up there. If we don't need to interpolate anything we can just read a file as `ByteString`?

**Comment by justinwoo** [comment]
I don't like the idea of using a template to dhall, I'd rather that dhall were just fixed to not erase comments or we just try to cram everything in a top level comment since package override sources are generally short anyway.

We should also look into loading up file contents to the CLI via https://github.com/snoyberg/file-embed

**Comment by f-f** [comment]
@justinwoo 

> I don't like the idea of using a template to dhall

Why so?

> I'd rather that dhall were just fixed to not erase comments

This needs work (currently marked as "help wanted" bug), because the parser throws away whitespace and comments. I guess we'd need a new AST constructor to wrap comments.

> we just try to cram everything in a top level comment

This doesn't feel like a good solution, as you want directions near the relevant code

**Comment by JordanMartinez** [comment]
@justinwoo I see the PR you made, but it doesn't include the meta-language instructions above. Could you explain why?

**Comment by JordanMartinez** [comment]
Sorry for my lack of response for such a long time.

> Do you want the whole body of your example in the comment? 
Yes, even if it's not in an ideal location, it still gives instructions for how to handle it.
If one puts it in the correct location and happens to run `dhall format`, it will remove the instructions, correct? In that case, it'd be good to put a warning before the rest of the content, too.

**Comment by justinwoo** [comment]
I guess if that's okay with you. Could you make a PR to the template file so you're attributed? https://github.com/justinwoo/spacchetti-cli/blob/master/templates/packages.dhall

**Comment by JordanMartinez** [comment]
Done. See justinwoo/spacchetti-cli#18

**Comment by justinwoo** [comment]
Thanks!
